### ISSUE TITLE
Failing on raspberry pi..how do I remove??

### ISSUE THREAD

**Issue by JourneyOver** [elmerfdz/OrganizrInstaller#214]
So I thought I'd do a smart thing and move my nginx stuff on over to my raspberry pi, but whenever I run the setup script it seems to fail on doing letsencrypt correctly and restarting nginx as well... So I was wondering what exactly would I need to do to remove everything..as I am just going to go back to running my server stuff on windows and you don't have an uninstall script for the ubuntu variant of your script :/

**Comment by elmerfdz** [comment]
Hi is that a fresh build of Raspbian on the Pi and which version of Raspbian (Stretch?).

I haven't tested LE cert gen on Raspbian, were there any errors? did the script complete?

What options did you select for the LE creation section? did you go ahead with this option (Is your domain on Cloudflare? [y/n] ) Most likely Raspbian is missing some repos that LE creation section needs.

Well to uninstall depends on what got installed, just search how to uninstall nginx, php, delete the Organizr folder from /var/www and certbot if that got installed.

**Comment by JourneyOver** [comment]
It's sorta fresh, been running for a month or two now with not a whole lot done on it other than running a few small things and yep running stretch with latest updates.

Yea there was errors but I sadly forgot to copy them down like a fool (tired as hell so forgive me), I know one of the errors was about my domain not doing wildcards for some reason, and it never seemed to actually create the certs or anything either when rerunning and doing a single domain. I chose `n` for the `Is your domain on Cloudflare? [y/n]` due to the fact I don't use cloudflare. As for the script completing it seemed like it did, it ended up with the whole press any button to return to menu thing after trying to restart nginx and failing and when I tried to access the site on my raspberry pi I got the whole 403 forbidden error in browser. 

Yep figured it out eventually, I had to uninstall nginx common as well since it didn't uninstall doing just nginx and from what I can tell got everything else removed as well now.

**Comment by JourneyOver** [comment]
Nope, nothing like that. Running things like ArchiSteamFarm (steam trading card farmer) and flexget is really about it server wise but don't have Apache or anything like that installed on my Pi.

**Comment by elmerfdz** [comment]
@JourneyOver so the default certbot package on Raspbian is quite an old one, I've pushed an update to support Raspbian, do you want to give it a go? I've tried wildcard and  single domain cert, both worked for me.

**Comment by JourneyOver** [comment]
@elmerfdz still fails on me sadly :/ this is my full setup from start (calling the script) to the end https://hastebin.com/raw/oxenojivit (I took out the sensitive stuff like domain name and email)

This is the systemctl status nginx.service information https://hastebin.com/raw/ponokomoka

**Comment by elmerfdz** [comment]
If you run this `sudo echo $(logname)` on terminal, does it return your username?

**Comment by JourneyOver** [comment]
Nope, it just returns `logname: no login name`

**Comment by elmerfdz** [comment]
weird! that should return your user. works on Ubuntu and also tested on Raspbian Stretch, try one more thing please
```
#!/bin/bash -e
echo $SUDO_USER
read
```
if you could try creating the above script and execute it, does it return your user? run as sudo please.

**Comment by JourneyOver** [comment]
yea that returns my user 
```
sudo bash /home/pi/Desktop/test.sh
pi
```
test.sh containing the 
```
#!/bin/bash -e
echo $SUDO_USER
read
```

**Comment by elmerfdz** [comment]
ok let me push a fix for that, you would've to uninstall nginx etc again before running :(

**Comment by JourneyOver** [comment]
Already uninstalled it all, should go about getting that uninstall script getting made ;P

**Comment by elmerfdz** [comment]
Yea! will be the next thing I focus on. Think there's something else going on here as well, don't think it's detecting it as Debian on your pi for some weird reason, could you check the output of this?
```
#!/bin/bash -e
debian_detect=$(cut -d: -f2 < <(lsb_release -i)| xargs)
echo $debian_detect
read

```

**Comment by JourneyOver** [comment]
```
pi@JourneysPi:~ $ sudo bash /home/pi/Desktop/test.sh
Raspbian
```
is what I get with the above 
```
#!/bin/bash -e
debian_detect=$(cut -d: -f2 < <(lsb_release -i)| xargs)
echo $debian_detect
read
```

**Comment by elmerfdz** [comment]
ahh! there you go! on the x86 version of Raspbian Stretch, it returns `Debian`

**Comment by elmerfdz** [comment]
Ok! could you try now? select option 5 -> experimental branch and then run option 4

**Comment by JourneyOver** [comment]
Running now, will report back when finished!

**Comment by elmerfdz** [comment]
@JourneyOver no new is good news, I guess..

**Comment by JourneyOver** [comment]
Well first install had some issues with PHP it kept throwing something about not replacing deleted files O_o and my /etc/php folder is pretty much empty other than a couple folders that are empty as well..

2nd install didn't throw any errors about the php stuff (folder is still empty though other than a couple folders that are still empty) .. installation seemed to be going well otherwise until I got to the http challenge and fail it for some reason even though I have everything set up correctly. and I still get the error
```
[....] Reloading nginx configuration (via systemctl): nginx.serviceJob for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
 failed!
```

**Comment by JourneyOver** [comment]
Sorry it took so long haha I tried multiple times trying to get everything to install :/ just seems like I'm destined to use nginx on windows or something since this is just throwing me for a loop on my Pi .-.

**Comment by JourneyOver** [comment]
I think I may have found the culprit at least for the http challenge but it's sadly something I may not be able to fix due to comcast and their shitty ass modem/router combo box.. 

For some reason it seems can't open ports on my Pi at all, be it in DMZ or port forwarding from the looks of it.. Testing open ports show that when I have nginx running on my pi the port still ended up closed even though I have both port forwarding and DMZ set for my Pi (and nginx isn't running anywhere else that could cause problems), but when doing port forwarding for my normal computer the ports open as soon as I start up nginx.

**Comment by elmerfdz** [comment]
Unlikely but have you tried rebooting the Pi after uninstalling Nginx

**Comment by JourneyOver** [comment]
Yea I made sure no leftover files where left anywhere, and I had rebooted the pi as well just for good measure.

**Comment by elmerfdz** [comment]
If you have no issues opening ports on other machines (does that include port 80 as well?), then there must be some service on your pi using those ports unless Comcast have blocked it on their network.

try this `sudo lsof -i -n -P` to see ports in use

**Comment by JourneyOver** [comment]
Comcast doesn't have port 80 / 443 blocked on their network, but like one issue I run into for sure is when doing port forwarding for my raspberry pi I am stuck having to only do DMZ variant as port forwarding seems to be completely broken as whenever I do port forward for just my raspberry pi I was get thrown an error message in comcast modem/router page saying to try again later no matter when I try to add it but it works for all my other computers..

As for that command, lsof doesn't seem to exist as I just get `sudo: lsof: command not found` Ontop of that idk what would be using port 80 as I haven't downloaded anything explicitly other than three things that run on port 1242, 3000, and 9091 (other than of course trying to run this organizrinstall stuff)

**Comment by elmerfdz** [comment]
Hmm are you on Organizr Discord? maybe check there if anyone is having/had issues port forwarding?

**Comment by JourneyOver** [comment]
yea I am, but I have a feeling they probably wouldn't be able to help much either, I just blame comcast for everything >.< I wish I could move away from having to use comcasts modem/router combo and go about using my own modem and router because then everything would be sooo much better and easier to setup dealing with ports and all that since it wouldn't be so damn broken but sadly I can't as I'm not the one paying for the whole internet stuff where I live .-. 

Honestly just think I'm going to say forget it and just go back to running nginx and all that on windows like I've been doing for the past week or two.

**Comment by elmerfdz** [comment]
@JourneyOver ok! 

btw added an option to uninstalll.

**Comment by JourneyOver** [comment]
Great, will test it out later after I take a nap :)

**Comment by JourneyOver** [comment]
Well that "nap" took a long time >.< the Uninstall option seems to work out great, didn't run into any errors or anything from what I could tell even doing a reinstallation and uninstallation so I say case/issue closed.
